### ISSUE TITLE
FPS Issues

### ISSUE THREAD

**Issue by AaronShea** [AaronShea/BLUI#23]
paulv2k4 experiences performance drops on large maps using the ExampleHUD. Currently unsure of the cause.

Quote from his forum post:

>Ok, so I did some testing and came to some rough conclusions.
>
>It seems this only works properly on a blank map and being run in a standalone process, in the editor window or (probably best) in a packaged game. Any other instance like "new editor window" drops the fps by at least 20 fps (in certain this is Slate/UMG issue). Put that with any decent size/complex map and your fps will soon become 10-20fps. (unchecking "use single process", does not seem to improve this)
>
>Also there is substantial fps dips occurring every 1-3 seconds bringing the fps down another 5-15fps, which is a little odd.
>
>There seems to be a slight 0.5s - 1.5s pause between a mouse click/hover/interaction and the page actually doing something.
>
>In that case I can not see this usable as a HUD but Menu UI will be fine as long as you keep the 3D background small (which games tend not to do anymore).
>
>I do know that Slate (UMG) is incredibly slow too which could be hindering the process (the profiler proves this). This made me wonder whether I should put this on a plane to see if it improves things.
>
>My concern is that if you were to ship the game and someone with a much worse CPU/GPU were using it, they would notice a more significant performance drop.

**Comment by AaronShea** [comment]
Hopefully this issue is somewhat resolved with pull #28

**Comment by AaronShea** [comment]
Performance was improved a bit more with commit 54e7fdfbaf9f39a76ec04706105efe171b2cee10
Waiting to hear feedback from users about this

**Comment by pargsoft** [comment]
Hi there,

saw this and thought I should say this commit did not solve this issue.

paulv2k4

**Comment by hitchcott** [comment]
link to forum post?

**Comment by AaronShea** [comment]
@hitchcott  https://forums.unrealengine.com/showthread.php?58192-PLUGIN-BLUI-Open-Source-HTML5-JS-CSS-HUD-UI&p=264359&viewfull=1#post264359

**Comment by hitchcott** [comment]
Thanks!

**Comment by buddytex** [comment]
The last few commits appear to have greatly improved FPS and general responsiveness, at least during my testing. (Rendering translucent material on a plane, UE4 4.7.6 Custom, Windows 7 64)

**Comment by AaronShea** [comment]
Seems I can finally close this issue! 

https://forums.unrealengine.com/showthread.php?58192-BLUI-Open-Source-HTML5-JS-CSS-HUD-UI&p=307255&viewfull=1#post307255

Thanks for the reports everyone!
